#pragma once

enum { EVT_BUMPER_INIT, EVT_BUMPER_PRESS, EVT_BUMPER_RELEASE, EVT_BUMPER_LIGHT_ON, EVT_BUMPER_LIGHT_OFF };
enum { ARG_BUMPER_COIL, ARG_BUMPER_LED }; 
enum { BUMPER_SCORE_ON, BUMPER_SCORE_OFF, BUMPER_LIGHT_ON, BUMPER_LIGHT_OFF };

const int16_t bumper_firmware[] = {
  EVT_BUMPER_INIT,
  EVT_BUMPER_PRESS,
  EVT_BUMPER_RELEASE,  
  EVT_BUMPER_LIGHT_ON, 
  EVT_BUMPER_LIGHT_OFF,
  -1,

  EVT_BUMPER_INIT,
  'P', -1, -1, 0,  // Not persistent 
  'L', -1, -1, ARG_BUMPER_COIL,
  'L', -1, -1, ARG_BUMPER_LED,
  -1,

  EVT_BUMPER_PRESS,
  'H', -1, -1, ARG_BUMPER_COIL,
  'J', ARG_BUMPER_LED, 0, 2,
  'T', -1, -1, BUMPER_SCORE_ON,
  'J', -1, -1, -1,
  'T', -1, -1, BUMPER_SCORE_OFF,
  -1,

  EVT_BUMPER_LIGHT_ON,
  'H', -1, -1, ARG_BUMPER_LED,
  'T', -1, -1, BUMPER_LIGHT_ON,
  -1,

  EVT_BUMPER_LIGHT_OFF,
  'L', -1, -1, ARG_BUMPER_LED,
  'T', -1, -1, BUMPER_LIGHT_OFF,
  -1,

  -1,
};

enum { EVT_FLIPPER_INIT, EVT_FLIPPER_PRESS, EVT_FLIPPER_RELEASE };
enum { ARG_FLIPPER_COIL }; 

const int16_t flipper_firmware[] = {
  EVT_FLIPPER_INIT,
  EVT_FLIPPER_PRESS,
  EVT_FLIPPER_RELEASE,  
  -1,

  EVT_FLIPPER_INIT,
  'P', -1, -1, 0,  // Not persistent
  'L', -1, -1, ARG_FLIPPER_COIL,
  -1,

  EVT_FLIPPER_PRESS,
  'H', -1, -1, ARG_FLIPPER_COIL,
  -1,

  EVT_FLIPPER_RELEASE,
  'L', -1, -1, ARG_FLIPPER_COIL,
  -1,

  -1,
};

enum { OXO_SET_SQUARE, OXO_MATCH_ROW, OXO_MATCH_ALL }; // Emitted events 

enum { // Received events
  EVT_OXO_INIT,
  EVT_OXO_PRESS,
  EVT_OXO_RELEASE,  
  EVT_OXO_1O, EVT_OXO_1X, EVT_OXO_2O, EVT_OXO_2X, EVT_OXO_3O, EVT_OXO_3X,             
  EVT_OXO_4, EVT_OXO_5, EVT_OXO_6, EVT_OXO_7, EVT_OXO_8, EVT_OXO_9, 
  EVT_OXO_TOGGLE, 
  SUB_OXO_MATCH123, SUB_OXO_MATCH456, SUB_OXO_MATCH789,
  SUB_OXO_MATCH147, SUB_OXO_MATCH258, SUB_OXO_MATCH369,
  SUB_OXO_MATCH159, SUB_OXO_MATCH357, 
  SUB_OXO_MATCHALL,
};

enum { // begin() argument placeholders
    ARG_OXO_1A, ARG_OXO_1B, ARG_OXO_1C, 
    ARG_OXO_2A, ARG_OXO_2B, ARG_OXO_2C,
    ARG_OXO_3A, ARG_OXO_3B, ARG_OXO_3C,
    ARG_OXO_4A, ARG_OXO_4B, ARG_OXO_4C,
    ARG_OXO_5A, ARG_OXO_5B, ARG_OXO_5C,
    ARG_OXO_6A, ARG_OXO_6B, ARG_OXO_6C,
    ARG_OXO_7A, ARG_OXO_7B, ARG_OXO_7C,
    ARG_OXO_8A, ARG_OXO_8B, ARG_OXO_8C,
    ARG_OXO_9A, ARG_OXO_9B, ARG_OXO_9C,
    ARG_OXO_O, ARG_OXO_X,
};

const int16_t tictactoe_firmware[] = {

  EVT_OXO_INIT,
  EVT_OXO_PRESS,
  EVT_OXO_RELEASE,  
  EVT_OXO_1O, EVT_OXO_1X, EVT_OXO_2O, EVT_OXO_2X, EVT_OXO_3O, EVT_OXO_3X,             
  EVT_OXO_4, EVT_OXO_5, EVT_OXO_6, EVT_OXO_7, EVT_OXO_8, EVT_OXO_9, 
  EVT_OXO_TOGGLE, 
  SUB_OXO_MATCH123, SUB_OXO_MATCH456, SUB_OXO_MATCH789,
  SUB_OXO_MATCH147, SUB_OXO_MATCH258, SUB_OXO_MATCH369,
  SUB_OXO_MATCH159, SUB_OXO_MATCH357, 
  SUB_OXO_MATCHALL,
  -1,

  EVT_OXO_INIT,
  'H', -1, -1, ARG_OXO_O, 
  'H', -1, -1, ARG_OXO_X, 
  -1,

  EVT_OXO_1O, 
  'J', ARG_OXO_1A, -1, 0, 
  'J', ARG_OXO_1B, -1, 0, 
  'H', -1, -1, ARG_OXO_1A, 
  'H', -1, -1, ARG_OXO_1C, 
  'S', -1, -1, SUB_OXO_MATCH123,
  'S', -1, -1, SUB_OXO_MATCH147,
  'S', -1, -1, SUB_OXO_MATCH159,
  'S', -1, -1, SUB_OXO_MATCHALL,
  -1,
  
  EVT_OXO_1X, 
  'J', ARG_OXO_1A, -1, 0, 
  'J', ARG_OXO_1B, -1, 0, 
  'H', -1, -1, ARG_OXO_1B, 
  'S', -1, -1, SUB_OXO_MATCH123,
  'S', -1, -1, SUB_OXO_MATCH147,
  'S', -1, -1, SUB_OXO_MATCH159,
  'S', -1, -1, SUB_OXO_MATCHALL,
  -1,
  
  EVT_OXO_2O, 
  'J', ARG_OXO_2A, -1, 0, 
  'J', ARG_OXO_2B, -1, 0, 
  'H', -1, -1, ARG_OXO_2A, 
  'H', -1, -1, ARG_OXO_2C, 
  'S', -1, -1, SUB_OXO_MATCH123,
  'S', -1, -1, SUB_OXO_MATCH258,
  'S', -1, -1, SUB_OXO_MATCHALL,
  -1,
  
  EVT_OXO_2X, 
  'J', ARG_OXO_2A, -1, 0, 
  'J', ARG_OXO_2B, -1, 0, 
  'H', -1, -1, ARG_OXO_2B, 
  'S', -1, -1, SUB_OXO_MATCH123,
  'S', -1, -1, SUB_OXO_MATCH258,
  'S', -1, -1, SUB_OXO_MATCHALL,
  -1,
  
  EVT_OXO_3O, 
  'J', ARG_OXO_3A, -1, 0, 
  'J', ARG_OXO_3B, -1, 0, 
  'H', -1, -1, ARG_OXO_3A, 
  'H', -1, -1, ARG_OXO_3C, 
  'S', -1, -1, SUB_OXO_MATCH123,
  'S', -1, -1, SUB_OXO_MATCH369,
  'S', -1, -1, SUB_OXO_MATCH357,
  'S', -1, -1, SUB_OXO_MATCHALL,
  -1,
  
  EVT_OXO_3X, 
  'J', ARG_OXO_3A, -1, 0, 
  'J', ARG_OXO_3B, -1, 0, 
  'H', -1, -1, ARG_OXO_3B, 
  'S', -1, -1, SUB_OXO_MATCH123,
  'S', -1, -1, SUB_OXO_MATCH369,
  'S', -1, -1, SUB_OXO_MATCH357,
  'S', -1, -1, SUB_OXO_MATCHALL,
  -1,

  EVT_OXO_4, 
  'J', ARG_OXO_4A, -1, 0, 
  'J', ARG_OXO_4B, -1, 0, 
  'H', ARG_OXO_X, ARG_OXO_4B, ARG_OXO_4A, 
  'H', ARG_OXO_X, ARG_OXO_4B, ARG_OXO_4C, 
  'S', -1, -1, SUB_OXO_MATCH147,
  'S', -1, -1, SUB_OXO_MATCH456,
  'S', -1, -1, SUB_OXO_MATCHALL,
  -1,
  
  EVT_OXO_5, 
  'J', ARG_OXO_5A, -1, 0, 
  'J', ARG_OXO_5B, -1, 0, 
  'H', ARG_OXO_X, ARG_OXO_5B, ARG_OXO_5A, 
  'H', ARG_OXO_X, ARG_OXO_5B, ARG_OXO_5C, 
  'S', -1, -1, SUB_OXO_MATCH159,
  'S', -1, -1, SUB_OXO_MATCH258,
  'S', -1, -1, SUB_OXO_MATCH357,
  'S', -1, -1, SUB_OXO_MATCH456,
  'S', -1, -1, SUB_OXO_MATCHALL,
  -1,
  
  EVT_OXO_6, 
  'J', ARG_OXO_6A, -1, 0, 
  'J', ARG_OXO_6B, -1, 0, 
  'H', ARG_OXO_X, ARG_OXO_6B, ARG_OXO_6A, 
  'H', ARG_OXO_X, ARG_OXO_6B, ARG_OXO_6C, 
  'S', -1, -1, SUB_OXO_MATCH369,
  'S', -1, -1, SUB_OXO_MATCH456,
  'S', -1, -1, SUB_OXO_MATCHALL,
  -1,
  
  EVT_OXO_7, 
  'J', ARG_OXO_7A, -1, 0, 
  'J', ARG_OXO_7B, -1, 0, 
  'H', ARG_OXO_X, ARG_OXO_7B, ARG_OXO_7A, 
  'H', ARG_OXO_X, ARG_OXO_7B, ARG_OXO_7C, 
  'S', -1, -1, SUB_OXO_MATCH789,
  'S', -1, -1, SUB_OXO_MATCH147,
  'S', -1, -1, SUB_OXO_MATCH357,
  'S', -1, -1, SUB_OXO_MATCHALL,
  -1,
  
  EVT_OXO_8, 
  'J', ARG_OXO_8A, -1, 0, 
  'J', ARG_OXO_8B, -1, 0, 
  'H', ARG_OXO_X, ARG_OXO_8B, ARG_OXO_8A, 
  'H', ARG_OXO_X, ARG_OXO_8B, ARG_OXO_8C, 
  'S', -1, -1, SUB_OXO_MATCH258,
  'S', -1, -1, SUB_OXO_MATCH789,
  'S', -1, -1, SUB_OXO_MATCHALL,
  -1,
  
  EVT_OXO_9, 
  'J', ARG_OXO_9A, -1, 0, 
  'J', ARG_OXO_9B, -1, 0, 
  'H', ARG_OXO_X, ARG_OXO_9B, ARG_OXO_9A, 
  'H', ARG_OXO_X, ARG_OXO_9B, ARG_OXO_9C, 
  'S', -1, -1, SUB_OXO_MATCH159,
  'S', -1, -1, SUB_OXO_MATCH369,
  'S', -1, -1, SUB_OXO_MATCH789,
  'S', -1, -1, SUB_OXO_MATCHALL,
  -1,

  EVT_OXO_TOGGLE, 
  'J', ARG_OXO_X, 0, 3, 
  'L', -1, -1, ARG_OXO_X, 
  'H', -1, -1, ARG_OXO_O, 
  'J', -1, -1, -1, 
  'L', -1, -1, ARG_OXO_O, 
  'H', -1, -1, ARG_OXO_X, 
  -1,    

  SUB_OXO_MATCH123,
  'J', ARG_OXO_1A, 0,  4,
  'J', ARG_OXO_2A, 0, -1,
  'J', ARG_OXO_3A, 3, -1,
  'J', ARG_OXO_1B, 0, -1,
  'J', ARG_OXO_2B, 0, -1,
  'J', ARG_OXO_3B, 0, -1,
  'T', -1, -1, OXO_MATCH_ROW,
  -1,
  
  SUB_OXO_MATCH456,
  'J', ARG_OXO_4A, 0,  4,
  'J', ARG_OXO_5A, 0, -1,
  'J', ARG_OXO_6A, 3, -1,
  'J', ARG_OXO_4B, 0, -1,
  'J', ARG_OXO_5B, 0, -1,
  'J', ARG_OXO_6B, 0, -1,
  'T', -1, -1, OXO_MATCH_ROW,
  -1,

  SUB_OXO_MATCH789,
  'J', ARG_OXO_7A, 0,  4,
  'J', ARG_OXO_8A, 0, -1,
  'J', ARG_OXO_9A, 3, -1,
  'J', ARG_OXO_7B, 0, -1,
  'J', ARG_OXO_8B, 0, -1,
  'J', ARG_OXO_9B, 0, -1,
  'T', -1, -1, OXO_MATCH_ROW,
  -1,

  SUB_OXO_MATCH147, 
  'J', ARG_OXO_1A, 0,  4,
  'J', ARG_OXO_4A, 0, -1,
  'J', ARG_OXO_7A, 3, -1,
  'J', ARG_OXO_1B, 0, -1,
  'J', ARG_OXO_4B, 0, -1,
  'J', ARG_OXO_7B, 0, -1,
  'T', -1, -1, OXO_MATCH_ROW,
  -1,
  
  SUB_OXO_MATCH258, 
  'J', ARG_OXO_2A, 0,  4,
  'J', ARG_OXO_5A, 0, -1,
  'J', ARG_OXO_8A, 3, -1,
  'J', ARG_OXO_1B, 0, -1,
  'J', ARG_OXO_5B, 0, -1,
  'J', ARG_OXO_8B, 0, -1,
  'T', -1, -1, OXO_MATCH_ROW,
  -1,
  
  SUB_OXO_MATCH369,
  'J', ARG_OXO_3A, 0,  4,
  'J', ARG_OXO_6A, 0, -1,
  'J', ARG_OXO_9A, 3, -1,
  'J', ARG_OXO_3B, 0, -1,
  'J', ARG_OXO_6B, 0, -1,
  'J', ARG_OXO_9B, 0, -1,
  'T', -1, -1, OXO_MATCH_ROW,
  -1,
  
  SUB_OXO_MATCH159, 
  'J', ARG_OXO_1A, 0,  4,
  'J', ARG_OXO_5A, 0, -1,
  'J', ARG_OXO_9A, 3, -1,
  'J', ARG_OXO_1B, 0, -1,
  'J', ARG_OXO_5B, 0, -1,
  'J', ARG_OXO_9B, 0, -1,
  'T', -1, -1, OXO_MATCH_ROW,
  -1,
  
  SUB_OXO_MATCH357,
  'J', ARG_OXO_3A, 0,  4,
  'J', ARG_OXO_5A, 0, -1,
  'J', ARG_OXO_7A, 3, -1,
  'J', ARG_OXO_3B, 0, -1,
  'J', ARG_OXO_5B, 0, -1,
  'J', ARG_OXO_7B, 0, -1,
  'T', -1, -1, OXO_MATCH_ROW,
  -1,

  SUB_OXO_MATCHALL,
  'T', -1, -1, OXO_SET_SQUARE, 
  'I', -1, -1, -1,
  'I', ARG_OXO_1A, 1, 0,
  'I', ARG_OXO_2A, 1, 0,
  'I', ARG_OXO_3A, 1, 0,
  'I', ARG_OXO_4A, 1, 0,
  'I', ARG_OXO_5A, 1, 0,
  'I', ARG_OXO_6A, 1, 0,
  'I', ARG_OXO_7A, 1, 0,
  'I', ARG_OXO_8A, 1, 0,
  'I', ARG_OXO_9A, 1, 0,
  'I', ARG_OXO_1B, 1, 0,
  'I', ARG_OXO_2B, 1, 0,
  'I', ARG_OXO_3B, 1, 0,
  'I', ARG_OXO_4B, 1, 0,
  'I', ARG_OXO_5B, 1, 0,
  'I', ARG_OXO_6B, 1, 0,
  'I', ARG_OXO_7B, 1, 0,
  'I', ARG_OXO_8B, 1, 0,
  'I', ARG_OXO_9B, 1, 0,
  'T', 9, OXO_MATCH_ALL, -1,
  -1,
    
  -1,
};      

  
