#pragma once

/* Custom firmware for the Atm_led_device programmable pinball device class
 *  
 *  tictactoe
 *  
 *  playfield.device( <switch-id> ); // Instantiates object
 *  playfield.device( <switch-id>, <led-id>, <firmware> ); // Initializes object
 *  
 */

namespace custom_firmware {

// Williams OXO tic-tac-toe game

enum { // Inputs & Subs
  IN_OXO_INIT,
  IN_OXO_1O, IN_OXO_1X, IN_OXO_2O, IN_OXO_2X, IN_OXO_3O, IN_OXO_3X,             
  IN_OXO_4, IN_OXO_5, IN_OXO_6, IN_OXO_7, IN_OXO_8, IN_OXO_9, 
  IN_OXO_TOGGLE, 
  SUB_OXO_MATCH_123, SUB_OXO_MATCH_456, SUB_OXO_MATCH_789,
  SUB_OXO_MATCH_147, SUB_OXO_MATCH_258, SUB_OXO_MATCH_369,
  SUB_OXO_MATCH_159, SUB_OXO_MATCH_357, 
  SUB_OXO_MATCH_ALL,
};

enum { OUT_OXO_SCORE, OUT_OXO_WIN_ROW, OUT_OXO_WIN_ALL }; // Outputs

enum { // Arguments (leds)
  ARG_OXO_1A, ARG_OXO_1B, ARG_OXO_1C, 
  ARG_OXO_2A, ARG_OXO_2B, ARG_OXO_2C,
  ARG_OXO_3A, ARG_OXO_3B, ARG_OXO_3C,
  ARG_OXO_4A, ARG_OXO_4B, ARG_OXO_4C,
  ARG_OXO_5A, ARG_OXO_5B, ARG_OXO_5C,
  ARG_OXO_6A, ARG_OXO_6B, ARG_OXO_6C,
  ARG_OXO_7A, ARG_OXO_7B, ARG_OXO_7C,
  ARG_OXO_8A, ARG_OXO_8B, ARG_OXO_8C,
  ARG_OXO_9A, ARG_OXO_9B, ARG_OXO_9C,
  ARG_OXO_X, ARG_OXO_O,
};

int16_t tictactoe_firmware[] = {
  IN_OXO_INIT,
  IN_OXO_1O, IN_OXO_1X, IN_OXO_2O, IN_OXO_2X, IN_OXO_3O, IN_OXO_3X,             
  IN_OXO_4, IN_OXO_5, IN_OXO_6, IN_OXO_7, IN_OXO_8, IN_OXO_9, 
  IN_OXO_TOGGLE, 
  SUB_OXO_MATCH_123, SUB_OXO_MATCH_456, SUB_OXO_MATCH_789,
  SUB_OXO_MATCH_147, SUB_OXO_MATCH_258, SUB_OXO_MATCH_369,
  SUB_OXO_MATCH_159, SUB_OXO_MATCH_357, 
  SUB_OXO_MATCH_ALL,
  -1,

  IN_OXO_INIT,
  'H', -1, -1, ARG_OXO_O, 
  'L', -1, -1, ARG_OXO_X, 
  -1,

  IN_OXO_1O, 
  'J', ARG_OXO_1A, -1, 0, 
  'J', ARG_OXO_1B, -1, 0, 
  'H', -1, -1, ARG_OXO_1A, 
  'H', -1, -1, ARG_OXO_1C, 
  'S', -1, -1, SUB_OXO_MATCH_123,
  'S', -1, -1, SUB_OXO_MATCH_147,
  'S', -1, -1, SUB_OXO_MATCH_159,
  'S', -1, -1, SUB_OXO_MATCH_ALL,
  -1,
  
  IN_OXO_1X, 
  'J', ARG_OXO_1A, -1, 0, 
  'J', ARG_OXO_1B, -1, 0, 
  'H', -1, -1, ARG_OXO_1B, 
  'S', -1, -1, SUB_OXO_MATCH_123,
  'S', -1, -1, SUB_OXO_MATCH_147,
  'S', -1, -1, SUB_OXO_MATCH_159,
  'S', -1, -1, SUB_OXO_MATCH_ALL,
  -1,
  
  IN_OXO_2O, 
  'J', ARG_OXO_2A, -1, 0, 
  'J', ARG_OXO_2B, -1, 0, 
  'H', -1, -1, ARG_OXO_2A, 
  'H', -1, -1, ARG_OXO_2C, 
  'S', -1, -1, SUB_OXO_MATCH_123,
  'S', -1, -1, SUB_OXO_MATCH_258,
  'S', -1, -1, SUB_OXO_MATCH_ALL,
  -1,
  
  IN_OXO_2X, 
  'J', ARG_OXO_2A, -1, 0, 
  'J', ARG_OXO_2B, -1, 0, 
  'H', -1, -1, ARG_OXO_2B, 
  'S', -1, -1, SUB_OXO_MATCH_123,
  'S', -1, -1, SUB_OXO_MATCH_258,
  'S', -1, -1, SUB_OXO_MATCH_ALL,
  -1,
  
  IN_OXO_3O, 
  'J', ARG_OXO_3A, -1, 0, 
  'J', ARG_OXO_3B, -1, 0, 
  'H', -1, -1, ARG_OXO_3A, 
  'H', -1, -1, ARG_OXO_3C, 
  'S', -1, -1, SUB_OXO_MATCH_123,
  'S', -1, -1, SUB_OXO_MATCH_369,
  'S', -1, -1, SUB_OXO_MATCH_357,
  'S', -1, -1, SUB_OXO_MATCH_ALL,
  -1,
  
  IN_OXO_3X, 
  'J', ARG_OXO_3A, -1, 0, 
  'J', ARG_OXO_3B, -1, 0, 
  'H', -1, -1, ARG_OXO_3B, 
  'S', -1, -1, SUB_OXO_MATCH_123,
  'S', -1, -1, SUB_OXO_MATCH_369,
  'S', -1, -1, SUB_OXO_MATCH_357,
  'S', -1, -1, SUB_OXO_MATCH_ALL,
  -1,

  IN_OXO_4, 
  'J', ARG_OXO_4A, -1, 0, 
  'J', ARG_OXO_4B, -1, 0, 
  'H', ARG_OXO_X, ARG_OXO_4B, ARG_OXO_4A, 
  'H', ARG_OXO_X, ARG_OXO_4B, ARG_OXO_4C, 
  'S', -1, -1, SUB_OXO_MATCH_147,
  'S', -1, -1, SUB_OXO_MATCH_456,
  'S', -1, -1, SUB_OXO_MATCH_ALL,
  -1,
  
  IN_OXO_5, 
  'J', ARG_OXO_5A, -1, 0, 
  'J', ARG_OXO_5B, -1, 0, 
  'H', ARG_OXO_X, ARG_OXO_5B, ARG_OXO_5A, 
  'H', ARG_OXO_X, ARG_OXO_5B, ARG_OXO_5C, 
  'S', -1, -1, SUB_OXO_MATCH_159,
  'S', -1, -1, SUB_OXO_MATCH_258,
  'S', -1, -1, SUB_OXO_MATCH_357,
  'S', -1, -1, SUB_OXO_MATCH_456,
  'S', -1, -1, SUB_OXO_MATCH_ALL,
  -1,
  
  IN_OXO_6, 
  'J', ARG_OXO_6A, -1, 0, 
  'J', ARG_OXO_6B, -1, 0, 
  'H', ARG_OXO_X, ARG_OXO_6B, ARG_OXO_6A, 
  'H', ARG_OXO_X, ARG_OXO_6B, ARG_OXO_6C, 
  'S', -1, -1, SUB_OXO_MATCH_369,
  'S', -1, -1, SUB_OXO_MATCH_456,
  'S', -1, -1, SUB_OXO_MATCH_ALL,
  -1,
  
  IN_OXO_7, 
  'J', ARG_OXO_7A, -1, 0, 
  'J', ARG_OXO_7B, -1, 0, 
  'H', ARG_OXO_X, ARG_OXO_7B, ARG_OXO_7A, 
  'H', ARG_OXO_X, ARG_OXO_7B, ARG_OXO_7C, 
  'S', -1, -1, SUB_OXO_MATCH_789,
  'S', -1, -1, SUB_OXO_MATCH_147,
  'S', -1, -1, SUB_OXO_MATCH_357,
  'S', -1, -1, SUB_OXO_MATCH_ALL,
  -1,
  
  IN_OXO_8, 
  'J', ARG_OXO_8A, -1, 0, 
  'J', ARG_OXO_8B, -1, 0, 
  'H', ARG_OXO_X, ARG_OXO_8B, ARG_OXO_8A, 
  'H', ARG_OXO_X, ARG_OXO_8B, ARG_OXO_8C, 
  'S', -1, -1, SUB_OXO_MATCH_258,
  'S', -1, -1, SUB_OXO_MATCH_789,
  'S', -1, -1, SUB_OXO_MATCH_ALL,
  -1,
  
  IN_OXO_9, 
  'J', ARG_OXO_9A, -1, 0, 
  'J', ARG_OXO_9B, -1, 0, 
  'H', ARG_OXO_X, ARG_OXO_9B, ARG_OXO_9A, 
  'H', ARG_OXO_X, ARG_OXO_9B, ARG_OXO_9C, 
  'S', -1, -1, SUB_OXO_MATCH_159,
  'S', -1, -1, SUB_OXO_MATCH_369,
  'S', -1, -1, SUB_OXO_MATCH_789,
  'S', -1, -1, SUB_OXO_MATCH_ALL,
  -1,

  IN_OXO_TOGGLE, 
  'J', ARG_OXO_X, 0, 3, 
  'L', -1, -1, ARG_OXO_X, 
  'H', -1, -1, ARG_OXO_O, 
  'J', -1, -1, -1, 
  'L', -1, -1, ARG_OXO_O, 
  'H', -1, -1, ARG_OXO_X, 
  -1,    

  SUB_OXO_MATCH_123,
  'J', ARG_OXO_1A, 0,  2,
  'J', ARG_OXO_2A, 0, -1,
  'J', ARG_OXO_3A, 3, -1,
  'J', ARG_OXO_1B, 0, -1,
  'J', ARG_OXO_2B, 0, -1,
  'J', ARG_OXO_3B, 0, -1,
  'T', -1, -1, OUT_OXO_WIN_ROW,
  -1,
  
  SUB_OXO_MATCH_456,
  'J', ARG_OXO_4A, 0,  2,
  'J', ARG_OXO_5A, 0, -1,
  'J', ARG_OXO_6A, 3, -1,
  'J', ARG_OXO_4B, 0, -1,
  'J', ARG_OXO_5B, 0, -1,
  'J', ARG_OXO_6B, 0, -1,
  'T', -1, -1, OUT_OXO_WIN_ROW,
  -1,

  SUB_OXO_MATCH_789,
  'J', ARG_OXO_7A, 0,  2,
  'J', ARG_OXO_8A, 0, -1,
  'J', ARG_OXO_9A, 3, -1,
  'J', ARG_OXO_7B, 0, -1,
  'J', ARG_OXO_8B, 0, -1,
  'J', ARG_OXO_9B, 0, -1,
  'T', -1, -1, OUT_OXO_WIN_ROW,
  -1,

  SUB_OXO_MATCH_147, 
  'J', ARG_OXO_1A, 0,  2,
  'J', ARG_OXO_4A, 0, -1,
  'J', ARG_OXO_7A, 3, -1,
  'J', ARG_OXO_1B, 0, -1,
  'J', ARG_OXO_4B, 0, -1,
  'J', ARG_OXO_7B, 0, -1,
  'T', -1, -1, OUT_OXO_WIN_ROW,
  -1,
  
  SUB_OXO_MATCH_258, 
  'J', ARG_OXO_2A, 0,  2,
  'J', ARG_OXO_5A, 0, -1,
  'J', ARG_OXO_8A, 3, -1,
  'J', ARG_OXO_2B, 0, -1,
  'J', ARG_OXO_5B, 0, -1,
  'J', ARG_OXO_8B, 0, -1,
  'T', -1, -1, OUT_OXO_WIN_ROW,
  -1,
  
  SUB_OXO_MATCH_369,
  'J', ARG_OXO_3A, 0,  2,
  'J', ARG_OXO_6A, 0, -1,
  'J', ARG_OXO_9A, 3, -1,
  'J', ARG_OXO_3B, 0, -1,
  'J', ARG_OXO_6B, 0, -1,
  'J', ARG_OXO_9B, 0, -1,
  'T', -1, -1, OUT_OXO_WIN_ROW,
  -1,
  
  SUB_OXO_MATCH_159, 
  'J', ARG_OXO_1A, 0,  2,
  'J', ARG_OXO_5A, 0, -1,
  'J', ARG_OXO_9A, 3, -1,
  'J', ARG_OXO_1B, 0, -1,
  'J', ARG_OXO_5B, 0, -1,
  'J', ARG_OXO_9B, 0, -1,
  'T', -1, -1, OUT_OXO_WIN_ROW,
  -1,
  
  SUB_OXO_MATCH_357,
  'J', ARG_OXO_3A, 0,  2,
  'J', ARG_OXO_5A, 0, -1,
  'J', ARG_OXO_7A, 3, -1,
  'J', ARG_OXO_3B, 0, -1,
  'J', ARG_OXO_5B, 0, -1,
  'J', ARG_OXO_7B, 0, -1,
  'T', -1, -1, OUT_OXO_WIN_ROW,
  -1,

  SUB_OXO_MATCH_ALL,
  'T', -1, -1, OUT_OXO_SCORE, 
  'I', -1, -1, -1,
  'I', ARG_OXO_1A, 1, 0,
  'I', ARG_OXO_2A, 1, 0,
  'I', ARG_OXO_3A, 1, 0,
  'I', ARG_OXO_4A, 1, 0,
  'I', ARG_OXO_5A, 1, 0,
  'I', ARG_OXO_6A, 1, 0,
  'I', ARG_OXO_7A, 1, 0,
  'I', ARG_OXO_8A, 1, 0,
  'I', ARG_OXO_9A, 1, 0,
  'I', ARG_OXO_1B, 1, 0,
  'I', ARG_OXO_2B, 1, 0,
  'I', ARG_OXO_3B, 1, 0,
  'I', ARG_OXO_4B, 1, 0,
  'I', ARG_OXO_5B, 1, 0,
  'I', ARG_OXO_6B, 1, 0,
  'I', ARG_OXO_7B, 1, 0,
  'I', ARG_OXO_8B, 1, 0,
  'I', ARG_OXO_9B, 1, 0,
  'T', 9, OUT_OXO_WIN_ALL, -1,
  -1,
    
  -1,
};      

};
